const { generateWAMessageFromContent, proto } = (await import('@whiskeysockets/baileys')).default

var handler = async (m, { conn, text}) => {

conn.reply(m.chat, `${emoji2} Looking for advice? Wait a moment....`, m)

conn.reply(m.chat, `*┏━_͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡_͜͡━┓*\n\n❥ *"${pickRandom(global.consejo)}"*\n\n*┗━_͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡_͜͡━┛*`, m)

}
handler.help = ['advice']
handler.tags = ['fun']
handler.command = ['advice']
handler.fail = null
handler.exp = 0
handler.group = true;
handler.register = true

export default handler

let hasil = Math.floor(Math.random() * 5000)
function pickRandom(list) {
return list[Math.floor(list.length * Math.random())]
}

global.consejo = ["Remember you can’t fail at being yourself (Wayne Dyer)",
"It’s always too early to give up (Jorge Álvarez Camacho)",
"Only one thing makes a dream impossible: the fear of failure (Paulo Coelho)",
"What you do today can improve all your tomorrows (Ralph Marston)",
"Small daily actions shape or undo character (Oscar Wilde)",
"Fall seven times and get up eight (Japanese Proverb)",
"For changes to have real value, they must be consistent and lasting (Anthony Robbins)",
"Nothing happens until something moves (Albert Einstein)",
"Being a good loser is learning how to win (Carl Sandburg)",
"All our dreams can come true if we have the courage to pursue them (Walt Disney)",
"He who transforms himself, transforms the world (Dalai Lama)",
"Your time is limited, so don’t waste it living someone else’s life… have the courage to follow your heart and intuition (Steve Jobs)",
"Most people spend more time and energy talking about problems than facing them (Henry Ford)",
"It’s not that we have little time, it’s that we waste a lot (Seneca)",
"To succeed, your desire for success must be greater than your fear of failure (Bill Cosby)",
"The true seeker grows and learns, discovering he is always mainly responsible for what happens (Jorge Bucay)",
"If opportunity doesn’t knock, build a door (Milton Berle)",
"There is always a better way to do it, find it (Thomas A. Edison)",
"It’s never too late to be the person you could have been (George Eliot)",
"When we are no longer able to change a situation, we are challenged to change ourselves (Viktor Frankl)",
"Defeat is not defeat until it is accepted as a reality in your own mind (Bruce Lee)",
"It’s hard to fail, but it’s worse never to have tried to succeed (Theodore Roosevelt)",
"Happiness is hidden in the waiting room of happiness (Eduard Punset)",
"Self-confidence is the first secret to success (Ralph Waldo Emerson)",
"A well-prepared man for battle has already achieved half the victory (Miguel de Cervantes)",
"We know what we are, but not what we can be (William Shakespeare)",
"Life begins at the end of your comfort zone (Neale Donald Walsch)",
"Anyone who is not making mistakes is not trying hard enough (Wess Roberts)",
"You must do the things you think you cannot do (Eleanor Roosevelt)",
"Trusting yourself doesn’t guarantee success, but not trusting guarantees failure (Albert Bandura)",
"The biggest mistake a person can make is being afraid of making a mistake (Elbert Hubbard)",
"From a small seed a mighty trunk can grow (Aeschylus)",
"The only way to find the limits of the possible is to go beyond them into the impossible (Arthur C. Clarke)",
"When life gives you a lemon, squeeze it and make lemonade (Clement Stone)",
"The measure of who we are is what we do with what we have (Vince Lombardi)",
"We become what we think (Earl Nightingale)",
"Only those who dare to fail greatly can achieve greatly (Robert F. Kennedy)",
"The power of imagination makes us infinite (John Muir)",
"Preparation is the key to success (Alexander Graham Bell)",
"The best way to predict the future is to invent it (Alan Key)",
"Things aren’t said, they’re done, because in doing them they speak for themselves (Woody Allen)",
"Give light and the darkness will disappear on its own (Erasmus)",
"To increase our self-esteem, we must first learn to live consciously, because this is the foundation of everything (Nathaniel Branden)",
"The problem is you think you have time (Buddha)",
"A person with a new idea is a joke until the idea succeeds (Mark Twain)",
"If you really want to see the Creator, become a creator (Deepak Chopra)",
"You don’t move forward by celebrating successes but by overcoming failures (Orison Swett Marden)",
"Fear can paralyze, dominate, isolate, but at a glimpse of courage it quickly gives way (Jose Antonio Marina)",
"Success isn’t random; it depends on effort (Sophocles)",
"Man needs difficulties because they are necessary to enjoy success (A.P.J. Abdul Kalam)",
"Sharpen the perception of everything that makes you feel good and immerse yourself in it (Martin Seligman)",
"Don’t get discouraged. Often the last key you try opens the lock (Anonymous)",
"A life unexamined is not worth living (Socrates)",
"Everything is growth and learning, continuous growth (Brian Weiss)",
"I’m always doing things I don’t know how to do, so I have to learn how to do them (Pablo Picasso)",
"A leader is someone who knows the way, walks the way, and shows the way (John C. Maxwell)",
"All success comes from working and knowing how to persevere (Og Mandino)",
"When it’s very dark you can see the stars (Persian Proverb)",
"The greatest pleasure in life is doing what people say you cannot do (Walter Bagehot)",
"Success is getting what you want. Happiness is wanting what you already have (Lair Ribeiro)",
"You can do anything but you can’t do everything (David Allen)",
"Only I can change my life. No one can do it for me (Carol Burnett)",
"Ninety percent of all failures are not truly defeated; they simply give up (Paul J. Meyer)",
"It always seems impossible… until it’s done (Nelson Mandela)",
"Every man dies. Not every man truly lives (William Wallace)",
"Nothing in life should be feared, only understood. Now is the time to understand more and fear less (Marie Curie)",
"We are what we repeatedly do. Excellence, then, is not an act but a habit (Aristotle)",
"Life is not a problem to be solved, but a reality to be experienced (Soren Kierkegaard)",
"Progress is only possible when looking far. Advancement comes when thinking big (Ortega y Gasset)",
"Victory is sweeter when you have known defeat (Malcolm Forbes)",
"What doesn’t kill you makes you stronger (Friedrich Nietzsche)",
"Only those who dare to suffer great failures can achieve great success (Will Smith)",
"The true entrepreneur is a doer, not a dreamer (Nolan Bushnell)",
"You have to train your brain to be positive just like you train your body (Shawn Achor)",
"Strength and growth come only through continuous effort and struggle (Napoleon Hill)",
"Out there, in some garage, an entrepreneur is forging a bullet with your company’s name on it (Gary Hamel)",
"When you have a dream, you have to grab it and never let go (Carol Burnett)",
"Look closely at the present you are building; it should resemble the future you are dreaming of (Alice Walker)",
"It’s not the strongest or the smartest species that survive, but those who best adapt to change (Darwin)",
"The more we do, the more we can do (William Hazlitt)",
"Life isn’t about finding yourself. Life is about creating yourself (George Bernard Shaw)",
"Luck is a dividend of sweat. The more you sweat, the luckier you get (Ray Kroc)",
"The most effective way to do it, is to do it (Amelia Earhart)",
"The meaning of life is giving life meaning (Ken Hudgins)",
"The key to success: want to win, know how to lose (Niccolò Machiavelli)",
"You can’t defeat the person who never gives up (Babe Ruth)",
"A dream is just a dream. A goal is a dream with a plan and a deadline (Harvey Mackay)",
"Success is a decision. Decide what to do with your life or someone else will decide for you (John Atkinson)",
"You have to make it happen (Denis Diderot)",
"Life is a play that doesn’t allow rehearsals… So sing, laugh, dance, cry, and live intensely every moment before the curtain falls and the play ends without applause (Charlie Chaplin)",
"If you mess up, it’s not your parents’ or teachers’ fault, so don’t whine about your mistakes and learn from them (Bill Gates)",
"I don’t run from a challenge because I’m afraid. I run toward it because the only way to escape fear is to crush it with your feet (Nadia Comaneci)",
"A good imperfect plan executed today is better than a perfect plan executed tomorrow (General Patton)",
"Determination is the starting point of all achievement (W. Clement Stone)",
"What isn’t started will never have an end (Johann Wolfgang von Goethe)",
"Choose a job you love, and you’ll never have to work a day in your life (Confucius)",
"The greatest risk is not taking any risk (Mark Zuckerberg)",
"I can accept failure; everyone fails at something. But I can’t accept not trying (Michael Jordan)",
"One of the biggest mistakes people make is forcing themselves to be interested in something. You don’t choose your passions; your passions choose you (Jeff Bezos)",
"Do it, or don’t do it, but don’t try (Yoda)",
"The main weapon for a country to be powerful is education (HacheJota)",
"Be yourself. Everyone else is already taken (Oscar Wilde)",
"Be the best version of yourself (Anonymous)",
"Be the change you want to see in the world (Mahatma Gandhi)",
"The scariest moment is always right before you start (Anonymous)",
"When you lose, don’t lose the lesson (Dalai Lama)",
"Desire it, expect it, dream it, but above all… do it! (HacheJota)",
"Don’t wait. The time will never be right (Napoleon Hill)",
"You can do more than you imagine, you are worth more than you think",
"Energy and persistence conquer all things (Benjamin Franklin)",
"Your best teacher is your biggest mistake (HacheJota)",
"You have to do the things you think you cannot do (Eleanor Roosevelt)",
"Every morning, get up with the idea of conquering the world",
"Don’t count the days, make the days count (Anonymous)"]