const { generateWAMessageFromContent, proto } = (await import('@whiskeysockets/baileys')).default

var handler = async (m, { conn, text}) => {

conn.reply(m.chat, `${emoji2} Looking for a compliment? Just wait a moment...`, m)

conn.reply(m.chat, `*┏━_͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡_͜͡━┓*\n\n❥ *"${pickRandom(global.piropo)}"*\n\n*┗━_͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡⚘-͜͡-͜͡-͜͡-͜͡-͜͡-͜͡_͜͡━┛*`, m)

}
handler.help = ['compliment']
handler.tags = ['fun']
handler.command = ['compliment']
handler.fail = null
handler.exp = 0
handler.group = true;
handler.register = true

export default handler

let hasil = Math.floor(Math.random() * 5000)
function pickRandom(list) {
return list[Math.floor(list.length * Math.random())]
}

global.piropo = ["If your body were a prison and your lips were chains, I’d happily serve my sentence there.",
"Yours is a two-for-one deal: beautiful *and* charming!",
"Science has really advanced—now even chocolates can walk!",
"For the moon I’d give a kiss, for the sun I’d give everything, but for the light in your eyes, I’d give my life and heart.",
"If I were a plane and you were an airport, I’d be landing on you all day long.",
"So many stars in the sky, and none shine like you.",
"I like coffee, but I prefer having ‘tea’ with you.",
"You’re not Google, but you have everything I’ve been searching for.",
"My desire for you doesn’t fade—it only grows.",
"I give you this flower, but none could ever match your beauty.",
"When they fine you for excessive beauty, I’ll pay your bail.",
"If every drop of water on your body were a kiss, I’d turn into a downpour.",
"You look like someone I’d invite to bed… and not sleep.",
"If your body were a prison and your arms chains, I’d gladly do time there.",
"How could I want to sleep if you’re on the other side of the screen?",
"I wish I were an ant so I could climb your balcony and whisper: gorgeous, sweetie, bombshell.",
"My life is missing life, light, and someone… and that someone is you.",
"Miss, if I knew how to swim, I’d dive into the pool of your eyes from the springboard of your lashes.",
"Excuse me, miss, they say you escaped from the box… –Which box? –The box of chocolates!",
"You’re so beautiful I’d give you a million kisses—and gladly take them back if you don’t want them.",
"You’re so stunning God would come down just to see you walk by.",
"You’re like a Sony camera—every time I look at you, I can’t stop smiling.",
"On a deserted island, I’d survive only on your kisses.",
"If you were winter rain, I’d close my umbrella just to feel you on me.",
"My feelings for you are so strong, I don’t mind being trapped in the web of your charm.",
"If I pinch you, you’d get mad; if you pinch me, I’d wake up smiling.",
"These aren’t words of gold or jewels, just heartfelt words for you.",
"I invite you to happiness—my treat.",
"When you walk, you don’t touch the ground, you caress it.",
"We’d look adorable on a wedding cake together.",
"So many lives in this world, and I only live in your eyes.",
"What number do I call to reach your heart for life?",
"I like you so much I don’t even know where to start.",
"Everyone notices your looks, but I prefer your heart.",
"Hi, if you like languages, I can teach you mine anytime.",
"Tell me where you walk so I can kiss the ground you step on, gorgeous!",
"Your beauty blinds me because it comes from your heart and shines in your eyes.",
"You’re the kind of person people wish upon stars for.",
"If anyone ever told you you’re beautiful, they lied—you’re gorgeous.",
"The sky is blue, cream is yellow, but your eyes are black—and they kill me softly.",
"If I were Columbus, I’d sail day and night to reach the depths of your heart.",
"I’ve crossed five streets, six including the alley, just one more to reach your heart.",
"If you were my girlfriend, I’d become an atheist—because I’d have nothing else to ask God for.",
"To a beautiful girl with her mother: What a pretty flower, too bad it comes with the pot!",
"If you give me a smile, you go from pretty to perfect.",
"What happened in heaven that the angels are falling?",
"I’m giving you a ticket… for excessive beauty.",
"Your parents must have loved each other a lot to make someone as beautiful as you.",
"Why is the sky cloudy? Because all the blue is in your eyes.",
"Do you have any injuries? It must hurt falling from heaven.",
"Your eyes are green, mine are brown; mine love you, yours… I don’t know yet.",
"When the day clouds over, I don’t miss the sun, because I have it in your smile.",
"A woman passes and says goodbye… I saw God in your eyes!",
"People elsewhere complain, but the sun is only here, because it’s in your eyes.",
"I’m on sale, gorgeous—two kisses for the price of one. God outdid himself creating you.",
"To love and you I met at the same time.",
"If beauty were time, you’d be 24 hours.",
"If you ever get lost, find yourself in my thoughts!",
"If loving you were a sin, I’d have hell guaranteed.",
"You’re the only thing missing in my life to make it perfect.",
"You’re the only star missing in the sky of my life!",
"Now that I know you, I have nothing else to wish for.",
"I’ll have to charge you rent—since you’ve been living in my dreams since I saw you.",
"I’d like to be your pillow, so you could hug me every morning.",
"I don’t speak pretty words, but a heartfelt verse: my love for you is infinite and true.",
"My love for you is so immense, I’d need another universe to hold it.",
"Math always tells the truth: you and I together forever.",
"How easy it would be to serve a sentence if your body were a prison and your arms chains.",
"My mother told me not to sin… but for you, I’d happily confess.",
"It’s not the whiskey or the beer—it’s you who’s making my head spin.",
"At night the moon shines, during the day the sun does, but your beautiful eyes light up my heart.",
"Don’t look for me, I prefer to stay lost in your gaze.",
"Some want the world, some want the sun, but I just want a corner of your heart.",
"I’ll stop loving you the day I find the needle I just threw into the sea.",
"Blessed are the drunk, for they will see you twice.",
"How far has science come, if flowers are already walking?",
"So many curves, and I have no brakes.",
"If Adam ate an apple for Eve, I’d eat a whole fruit store for you.",
"If I were an astronaut, I’d take you to Pluto—but since I’m not, you’ll always be in my heart.",
"You must be an atheist, because you’re exactly how you want to be, not how God commands.",
"Science is so advanced, even chocolates can walk.",
"Which toy store did you escape from, doll?",
"I walked past your house yesterday and you threw me a brick… tomorrow I’ll come back to build you a castle.",
"Did it hurt falling from heaven, little angel?",
"Your mom must be a baker, because a candy like you doesn’t come easy.",
"Your dad must be a pirate, because you’re a treasure!",
"I always hear people say Disneyland is the happiest place on earth. But I wonder if they’ve ever been next to you?",
"For some reason, I was feeling a little down today. But when I saw you, you excited me and all my sadness vanished.",
"Do you know if there’s an airport nearby, or is my heart just taking off?",
"Was your dad a boxer? No? Then I must tell you—you’re a knockout!",
"Oh my God! Do you have an extra heart? Because mine just got stolen.",
"Besides being incredibly sexy, what do you do?",
"Did the sun just come out, or did you just smile at me?",
"You have to kiss me if I’m wrong, do dinosaurs still exist?",
"Hey, you’re pretty, and I’m cute. Together, we’d be really cute.",
"I’m sure your name must be Google. Why? Because you have everything I’ve been searching for!",
"I’m sure your dad is an alien! I’ve never seen anything like you on Earth.",
"Please don’t be scared by this question… was your dad a thief? Because someone stole the stars from the sky and put them in your eyes, babe.",
"Do you have a pencil and eraser? I want to erase your past and write our future.",
"You don’t need keys to drive me crazy.",
"Sorry, but you owe me a drink. Why? Because when I looked at you, I got hypnotized and spilled mine!",
"You must be a broom, because you just knocked me over.",
"Go ahead, feel my shirt. It’s made of boyfriend material!",
"Do you believe in love at first sight? Or should I walk by again?",
"I’m studying important dates in history. Want to be one of them?",
"Excuse me… Are you a loan? Because you have all my interest!",
"If I’m vinegar, then you must be baking soda. Because you make me fizz inside!",
"For a second I thought I died and went to heaven. Now I see I’m alive, but heaven has been brought to me.",
"Can I have a kiss? I swear I’ll give it back.",
"Please stop being so sweet! You’re giving me a toothache!",
"You’re like my favorite cup of coffee—hot and irresistible!",
"Are you a camera? Because every time I look at you, I smile.",
"Do you know what would really look good on you? Me.",
"I don’t need Twitter, I’m already following you.",
"I need your name to know what to shout tonight.",
"It’s official! You’re on my to-do list tonight, impossible to escape!",
"Do you know what’s on the menu for delicious? You and me, baby!",
"Your lips look lonely and dry. Let me introduce you to mine.",
"If nothing lasts forever, will you be my forever?",
"Do you have a name, or can I call you mine?",
"Have you been covered in bees recently? I just assumed, because you look sweeter than honey.",
"There must be something wrong with my eyes. I can’t stop staring at you.",
"You’re like fire. Because you’re super hot.",
"My friends bet I couldn’t talk to the prettiest girl in the bar. Well, now… what should we do with their money?",
"Well, here I am, your wish has been granted. Now… what are the other two wishes for the lamp genie?",
"Look… I’m no mathematician, but I’m pretty good with numbers. Why don’t you give me yours and I’ll show you what I can do.",
"Are you a time traveler? Because I see you in my future!",
"If you and I were socks, we’d make a perfect pair!",
"Besides being incredibly beautiful, what do you do?",
"Want a raisin? No? How about a date?",
"I may not be a photographer, but I can totally picture us together.",
"You must be a magician, right? It’s weird—every time I look at you, magically everyone else disappears!"]